# Disable padding
padding = [0]

[window]
opacity = 1.0
blur = false

# Monokai Classic colorscheme
[colors]
background = '#272822'
foreground = '#F8F8F2'
cursor = '#F8F8F2'
vi-cursor = '#F8F8F2'
selection-background = '#3b3c35'
selection-foreground = '#F8F8F2'
search-match-background = '#3b3c35'
search-match-foreground = '#F8F8F2'
search-focused-match-background = '#75715E'
search-focused-match-foreground = '#F8F8F2'
tabs = '#75715E'          
tabs-active = '#F8F8F2'   
bar = '#272822'           
split = '#272822' 

# Regular colors (ANSI)
black = '#21221d'
red = '#f92672'
green = '#a6e22e'
yellow = '#e6db74'
blue = '#94e4f4'
magenta = '#ae81ff'
cyan = '#66d9ef'
white = '#F8F8F2'

# Dim colors
dim-black = '#1E1F1C'
dim-red = '#C3074A'
dim-green = '#7F9F1F'
dim-yellow = '#BFAF5B'
dim-blue = '#4A9CB2'
dim-magenta = '#8A65CC'
dim-cyan = '#80B8B3'
dim-white = '#C1C1C1'

# Light colors (Brights)
light-black = '#75715E'
light-red = '#f858a2'
light-green = '#99cc66'
light-yellow = '#f0d264'
light-blue = '#94e4f4'
light-magenta = '#b294bb'
light-cyan = '#66cccc'
light-white = '#ffffff'


[fonts]
family = "CaskaydiaCove Nerd Font Mono"
size = 14

[fonts.regular]
family = "CaskaydiaCove Nerd Font Mono"
style = "Normal"
weight = 400
width = "Normal"

[fonts.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Normal"
weight = 800
width = "Normal"

[fonts.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"
width = "Normal"
weight = 400

[fonts.bold-italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"
width = "Normal"
weight = 800

[cursor]
shape = "block"
blinking = false

[shell]
program = "pwsh.exe"
args = ["-NoLogo"]
