return {
	"nvim-tree/nvim-tree.lua",
	cmd = "NvimTreeToggle",
	lazy = true,
	config = function()
		require("nvim-tree").setup({
			sync_root_with_cwd = false,
			update_cwd = false,
			hijack_netrw = false,
			reload_on_bufenter = false,

			diagnostics = { enable = false },
			filters = {
				custom = {
					"node_modules",
					"__pycache__",
					".git",
					"dist",
					"build",
					"target",
					"out",
					"bin",
					"obj",
					"coverage",
					"vendor",
					".venv",
					"venv",
					"*.egg-info",
					"*.tmp",
					"*.temp",
					"*.cache",
					".DS_Store",
					"*.swp",
					"*.swo",
					"*.bak",
					"*.backup",
					"*.pyc",
					"*.pyo",
					"*.class",
					"*.o",
					"*.obj",
					"*.jpg",
					"*.jpeg",
					"*.png",
					"*.gif",
					"*.svg",
					"*.mp4",
					"*.mkv",
					"*.avi",
					"*.mp3",
					"*.wav",
					"*.zip",
					"*.tar",
					"*.gz",
					"*.7z",
					"*.exe",
					"*.dll",
					"*.so",
					"*.dylib",
					"*.pdf",
					"package-lock.json",
					"yarn.lock",
					"pnpm-lock.yaml",
					"*.min.js",
					"*.min.css",
					"*.map",
					"*.db",
					"*.sqlite",
					"*.sqlite3",
				},
				dotfiles = true,
			},
		})
	end,
}
